<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.340">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Frank Agyemang">
<meta name="author" content="Dr.&nbsp;Reka Howard">
<meta name="author" content="Dr.&nbsp;Walter Stroup">
<meta name="author" content="Dr.&nbsp;Erin Blankenship">

<title>Exploring a Split-Plot Design With a Control: Irrigation and Weed Control Example in R</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="split_plot_irrigation_weed_control_R_files/libs/clipboard/clipboard.min.js"></script>
<script src="split_plot_irrigation_weed_control_R_files/libs/quarto-html/quarto.js"></script>
<script src="split_plot_irrigation_weed_control_R_files/libs/quarto-html/popper.min.js"></script>
<script src="split_plot_irrigation_weed_control_R_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="split_plot_irrigation_weed_control_R_files/libs/quarto-html/anchor.min.js"></script>
<link href="split_plot_irrigation_weed_control_R_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="split_plot_irrigation_weed_control_R_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="split_plot_irrigation_weed_control_R_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="split_plot_irrigation_weed_control_R_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="split_plot_irrigation_weed_control_R_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article toc-left">
<div id="quarto-sidebar-toc-left" class="sidebar toc-left">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction">Introduction</a></li>
  <li><a href="#statistical-challenge" id="toc-statistical-challenge" class="nav-link" data-scroll-target="#statistical-challenge">Statistical Challenge</a></li>
  <li><a href="#exploratory-data-analysis" id="toc-exploratory-data-analysis" class="nav-link" data-scroll-target="#exploratory-data-analysis">Exploratory Data Analysis</a>
  <ul class="collapse">
  <li><a href="#data-description" id="toc-data-description" class="nav-link" data-scroll-target="#data-description">Data Description</a></li>
  <li><a href="#simulated-data" id="toc-simulated-data" class="nav-link" data-scroll-target="#simulated-data">Simulated Data</a></li>
  <li><a href="#histogram-of-corn-yield" id="toc-histogram-of-corn-yield" class="nav-link" data-scroll-target="#histogram-of-corn-yield">Histogram of Corn Yield</a></li>
  <li><a href="#boxplot-of-corn-yield-and-treatments" id="toc-boxplot-of-corn-yield-and-treatments" class="nav-link" data-scroll-target="#boxplot-of-corn-yield-and-treatments">Boxplot of Corn Yield and Treatments</a></li>
  <li><a href="#interaction-plot" id="toc-interaction-plot" class="nav-link" data-scroll-target="#interaction-plot">Interaction Plot</a></li>
  </ul></li>
  <li><a href="#advanced-analysis" id="toc-advanced-analysis" class="nav-link" data-scroll-target="#advanced-analysis">Advanced Analysis</a></li>
  <li><a href="#statistical-model" id="toc-statistical-model" class="nav-link" data-scroll-target="#statistical-model">Statistical Model</a>
  <ul class="collapse">
  <li><a href="#covariance-parameter-estimates" id="toc-covariance-parameter-estimates" class="nav-link" data-scroll-target="#covariance-parameter-estimates">Covariance Parameter Estimates</a></li>
  <li><a href="#anova-table" id="toc-anova-table" class="nav-link" data-scroll-target="#anova-table">ANOVA Table</a></li>
  <li><a href="#estimated-marginal-means-for-each-irrigation-by-weed-treatment-combination" id="toc-estimated-marginal-means-for-each-irrigation-by-weed-treatment-combination" class="nav-link" data-scroll-target="#estimated-marginal-means-for-each-irrigation-by-weed-treatment-combination">Estimated Marginal Means for each Irrigation-by-Weed Treatment Combination</a></li>
  <li><a href="#main-effects-for-weed-treatments" id="toc-main-effects-for-weed-treatments" class="nav-link" data-scroll-target="#main-effects-for-weed-treatments">Main Effects for Weed Treatments</a></li>
  <li><a href="#main-effects-of-treatments-and-control" id="toc-main-effects-of-treatments-and-control" class="nav-link" data-scroll-target="#main-effects-of-treatments-and-control">Main Effects of Treatments and Control</a></li>
  <li><a href="#difference-of-main-effect-between-treatment-and-control" id="toc-difference-of-main-effect-between-treatment-and-control" class="nav-link" data-scroll-target="#difference-of-main-effect-between-treatment-and-control">Difference of Main Effect Between Treatment and Control</a></li>
  </ul></li>
  <li><a href="#simple-effects" id="toc-simple-effects" class="nav-link" data-scroll-target="#simple-effects">Simple Effects</a>
  <ul class="collapse">
  <li><a href="#simple-effect-of-weed-treatments-in-each-irrigation-method" id="toc-simple-effect-of-weed-treatments-in-each-irrigation-method" class="nav-link" data-scroll-target="#simple-effect-of-weed-treatments-in-each-irrigation-method">Simple Effect of Weed Treatments in each Irrigation Method</a></li>
  <li><a href="#comparison-of-weed-treatments-in-each-irrigation-method" id="toc-comparison-of-weed-treatments-in-each-irrigation-method" class="nav-link" data-scroll-target="#comparison-of-weed-treatments-in-each-irrigation-method">Comparison of Weed Treatments in each Irrigation Method</a></li>
  <li><a href="#main-effects-of-irrigation-methods" id="toc-main-effects-of-irrigation-methods" class="nav-link" data-scroll-target="#main-effects-of-irrigation-methods">Main Effects of Irrigation Methods</a></li>
  <li><a href="#comparison-of-irrigation-methods" id="toc-comparison-of-irrigation-methods" class="nav-link" data-scroll-target="#comparison-of-irrigation-methods">Comparison of Irrigation Methods</a></li>
  </ul></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion">Conclusion</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="split_plot_irrigation_weed_control_R.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
</div>
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Exploring a Split-Plot Design With a Control: Irrigation and Weed Control Example in R</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Frank Agyemang </p>
             <p>Dr.&nbsp;Reka Howard </p>
             <p>Dr.&nbsp;Walter Stroup </p>
             <p>Dr.&nbsp;Erin Blankenship </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="introduction" class="level2">
<h2 class="anchored" data-anchor-id="introduction">Introduction</h2>
<p>Split-plot experiments are commonly used when one treatment factor is harder, more expensive, or less practical to randomize than another treatment factor. In a split-plot design, the hard-to-change factor is assigned to large experimental units called whole plots. The easier-to-change factor is then assigned to smaller experimental units called split plots or subplots within each whole plot.</p>
<p>In this example, researchers are interested in evaluating the effect of irrigation method and weed treatment on corn yield. The whole plot factor is irrigation method, with two levels: drip irrigation and sprinkler irrigation. Irrigation is treated as the whole plot factor because it is difficult to apply different irrigation systems to very small plots. The split plot factor is weed treatment, with two active treatment levels: herbicide A and herbicide B.</p>
<p>In addition to the factorial treatment combinations, the researchers include a control treatment. The control represents plots that do not receive any irrigation-treatment combination or weed treatment being studied. Therefore, the control is not considered a level of the weed factor. Instead, it serves as an additional reference treatment outside the split-plot factorial structure.</p>
<p>The study is conducted using blocks. Each block represents a field section that may differ in soil fertility, moisture, slope, or other background conditions. Within each block, the two irrigation methods are randomly assigned to whole plots. Within each irrigation whole plot, the active weed treatments are randomly assigned to subplots. The control treatment is included separately within each block so that the factorial treatment combinations can be compared with a baseline condition.</p>
<p>This design allows researchers to answer several important questions. First, does irrigation method affect corn yield among the factorial treatments? Second, does weed treatment affect corn yield among the factorial treatments? Third, does the effect of weed treatment depend on the irrigation method? Finally, do the factorial treatment combinations differ from the control treatment?</p>
</section>
<section id="statistical-challenge" class="level2">
<h2 class="anchored" data-anchor-id="statistical-challenge">Statistical Challenge</h2>
<p>The statistical challenge in a split-plot design with a control is that the treatment factors are not all randomized at the same experimental-unit level. The whole plot factor, irrigation method, is randomized to whole plots within blocks. The split plot factor, weed treatment, is randomized to subplots within each irrigation whole plot. Because of this randomization structure, the analysis must account for both whole plot error and subplot error.</p>
<p>The whole plot error is used to evaluate the irrigation effect because irrigation is applied to the larger whole plots. The subplot error is used to evaluate the weed effect and the irrigation by weed interaction because weed treatments are applied to the smaller subplots. If the data are analyzed as a regular factorial design, the model ignores the split-plot structure and may use the wrong error term, especially for testing the irrigation effect.</p>
<p>A second challenge is that the control is not part of the factorial treatment structure. In this example, the factorial portion of the design contains the irrigation-by-weed combinations. The control is added as an extra treatment and does not have an irrigation level or weed level in the same way as the factorial treatments. Because of this, the control should not be forced into the irrigation or weed factors.</p>
<p>Instead, the control should be modeled separately using a control indicator variable. This allows the model to estimate the factorial effects of irrigation, weed treatment, and their interaction using only the factorial treatment combinations. At the same time, it allows researchers to compare the control treatment with the average of the factorial treatments or with specific treatment combinations. This preserves the correct interpretation of the control as a baseline treatment rather than incorrectly treating it as one level of the split-plot factor.</p>
</section>
<section id="exploratory-data-analysis" class="level2">
<h2 class="anchored" data-anchor-id="exploratory-data-analysis">Exploratory Data Analysis</h2>
<p>In this example, the response variable is corn yield. The yield values are simulated to demonstrate the correct structure of a split-plot design with a control as an extra treatment. The design includes six blocks. Each block represents a field section that may differ in soil fertility, moisture, slope, or other background conditions.</p>
<p>Within each block, the two irrigation methods are randomly assigned to whole plots. The irrigation methods are drip irrigation and sprinkler irrigation. Within each irrigation whole plot, the two active weed treatments are randomly assigned to subplots. The active weed treatments are herbicide A and herbicide B.</p>
<p>In addition to the four irrigation-by-weed treatment combinations, a control treatment is included in each block. The control treatment represents a baseline condition and is not part of the irrigation-by-weed factorial structure. Therefore, the control does not have an irrigation level or an active weed level in the same way as the factorial treatment combinations.</p>
<p>The exploratory data analysis describes the treatment layout, the simulated data, the distribution of corn yield, and the relationship between irrigation method and weed treatment. The control is displayed separately as a reference treatment.</p>
<section id="data-description" class="level3">
<h3 class="anchored" data-anchor-id="data-description">Data Description</h3>
<p>There are 30 observations in the simulated data set. This includes six blocks, with five treatment conditions in each block. The five treatment conditions are the four factorial treatment combinations plus one control treatment.</p>
<p>The factorial portion of the design contains two irrigation methods and two active weed treatments. Therefore, the factorial treatment structure has four treatment combinations: drip irrigation with herbicide A, drip irrigation with herbicide B, sprinkler irrigation with herbicide A, and sprinkler irrigation with herbicide B. Each factorial treatment combination has six observations, one from each block.</p>
<p>The control treatment is included once in each block, giving six control observations. The control is treated as an extra treatment outside the factorial structure. The response variable is corn yield.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading required packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lme4)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(lmerTest)</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(emmeans)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Table 1 shows the layout of the experiment. Irrigation method is the whole plot factor because it is assigned to larger plots. weed treatment is the split plot factor because it is assigned to smaller subplots within each irrigation whole plot. And then, the control is the fifth treatment applied to each block.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Experimental Layout for the Split-Plot Design With Control as an Extra Treatment</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 6%">
<col style="width: 45%">
<col style="width: 21%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Irrigation Method</th>
<th style="text-align: left;">weed Treatment</th>
<th style="text-align: left;">Control</th>
<th style="text-align: left;">Description</th>
<th style="text-align: left;">Replicates</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: left;">Drip irrigation with herbicide A</td>
<td style="text-align: left;">1 per block × 6 blocks = 6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: left;">Drip irrigation with herbicide B</td>
<td style="text-align: left;">1 per block × 6 blocks = 6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: left;">Sprinkler irrigation with herbicide A</td>
<td style="text-align: left;">1 per block × 6 blocks = 6</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: left;">Sprinkler irrigation with herbicide B</td>
<td style="text-align: left;">1 per block × 6 blocks = 6</td>
</tr>
<tr class="odd">
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: left;">Control treatment with no irrigation-by-weed combination</td>
<td style="text-align: left;">1 per block × 6 blocks = 6</td>
</tr>
</tbody>
</table>
<p></p>
</div>
</div>
</section>
<section id="simulated-data" class="level3">
<h3 class="anchored" data-anchor-id="simulated-data">Simulated Data</h3>
<p>The code chunk below creates a simulated data set for a split-plot design with a control as an extra treatment. First, it creates six blocks. Then it creates the factorial treatment combinations using two irrigation methods and two active weed treatments. These four combinations are drip irrigation with herbicide A, drip irrigation with herbicide B, sprinkler irrigation with herbicide A, and sprinkler irrigation with herbicide B.</p>
<p>After creating the factorial treatment combinations, the code adds one control treatment to each block. The control is coded as <code>"None"</code> for irrigation and <code>"None"</code> for weed treatment because it is not part of the factorial structure. A new variable called <code>Control</code> is then created to identify whether an observation belongs to the control group or to the factorial treatment group.</p>
<p>The code also adds random block effects and whole plot effects. The block effects represent natural differences among field sections. The whole plot effects represent extra variation among whole plots that receive different irrigation methods. Since the control is outside the factorial irrigation structure, it does not receive an irrigation whole plot effect.</p>
<p>Finally, the code simulates corn yield by combining a baseline yield, block effects, irrigation effects, weed effects, an interaction effect, the separate control effect, whole plot variation, and random error. The resulting data are displayed in a table with block, irrigation method, weed treatment, control indicator, and corn yield. Table 2 shows the final output of the simulated data.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Set seed for reproducibility</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># This makes sure that the same simulated data are produced</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># each time the code is run</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">2026</span>)</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Define the six blocks used in the experiment</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>blocks <span class="ot">&lt;-</span> <span class="fu">factor</span>(<span class="dv">1</span><span class="sc">:</span><span class="dv">6</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Create the factorial part of the split-plot design.</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>factorial_layout <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">Block =</span> blocks,</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">Irrigation =</span> <span class="fu">c</span>(<span class="st">"Drip"</span>, <span class="st">"Sprinkler"</span>),</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">Weed =</span> <span class="fu">c</span>(<span class="st">"Herbicide A"</span>, <span class="st">"Herbicide B"</span>)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Add the control treatment once in each block</span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Therefore, Irrigation and Weed are both coded as "None" for the control</span></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>control_layout <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">Block =</span> blocks,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">Irrigation =</span> <span class="st">"None"</span>,</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">Weed =</span> <span class="st">"None"</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Combine the factorial treatment combinations and the control treatment</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>splt_df <span class="ot">&lt;-</span> <span class="fu">rbind</span>(factorial_layout, control_layout)</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a control indicator variable</span></span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Control <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a>  splt_df<span class="sc">$</span>Irrigation <span class="sc">==</span> <span class="st">"None"</span> <span class="sc">&amp;</span> splt_df<span class="sc">$</span>Weed <span class="sc">==</span> <span class="st">"None"</span>,</span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a>  <span class="st">"y"</span>,</span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>  <span class="st">"n"</span></span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert the variables to factors</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Block <span class="ot">&lt;-</span> <span class="fu">factor</span>(splt_df<span class="sc">$</span>Block)</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Irrigation <span class="ot">&lt;-</span> <span class="fu">factor</span>(splt_df<span class="sc">$</span>Irrigation)</span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Weed <span class="ot">&lt;-</span> <span class="fu">factor</span>(splt_df<span class="sc">$</span>Weed)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Control <span class="ot">&lt;-</span> <span class="fu">factor</span>(splt_df<span class="sc">$</span>Control)</span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate block effects</span></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>n_blocks <span class="ot">&lt;-</span> <span class="fu">length</span>(<span class="fu">unique</span>(splt_df<span class="sc">$</span>Block))</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>block_effects <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(</span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>  n_blocks,</span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="dv">0</span>,</span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="dv">4</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="co"># Create whole plot units for only the factorial portion of the design</span></span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>whole_plot_units <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>  <span class="at">Block =</span> blocks,</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>  <span class="at">Irrigation =</span> <span class="fu">c</span>(<span class="st">"Drip"</span>, <span class="st">"Sprinkler"</span>)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a whole plot label by combining block and irrigation method</span></span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>whole_plot_units<span class="sc">$</span>WholePlot <span class="ot">&lt;-</span> <span class="fu">paste</span>(</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>  whole_plot_units<span class="sc">$</span>Block,</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>  whole_plot_units<span class="sc">$</span>Irrigation,</span>
<span id="cb2-63"><a href="#cb2-63" aria-hidden="true" tabindex="-1"></a>  <span class="at">sep =</span> <span class="st">"_"</span></span>
<span id="cb2-64"><a href="#cb2-64" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-65"><a href="#cb2-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-66"><a href="#cb2-66" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb2-67"><a href="#cb2-67" aria-hidden="true" tabindex="-1"></a><span class="co"># Generate whole plot effects</span></span>
<span id="cb2-68"><a href="#cb2-68" aria-hidden="true" tabindex="-1"></a><span class="co"># These represent extra variation among whole plots within blocks.</span></span>
<span id="cb2-69"><a href="#cb2-69" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------------------#</span></span>
<span id="cb2-70"><a href="#cb2-70" aria-hidden="true" tabindex="-1"></a>whole_plot_units<span class="sc">$</span>WholePlotEffect <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(</span>
<span id="cb2-71"><a href="#cb2-71" aria-hidden="true" tabindex="-1"></a>  <span class="fu">nrow</span>(whole_plot_units),</span>
<span id="cb2-72"><a href="#cb2-72" aria-hidden="true" tabindex="-1"></a>  <span class="at">mean =</span> <span class="dv">0</span>,</span>
<span id="cb2-73"><a href="#cb2-73" aria-hidden="true" tabindex="-1"></a>  <span class="at">sd =</span> <span class="dv">3</span></span>
<span id="cb2-74"><a href="#cb2-74" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-75"><a href="#cb2-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-76"><a href="#cb2-76" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a whole plot identifier to the main data set.</span></span>
<span id="cb2-77"><a href="#cb2-77" aria-hidden="true" tabindex="-1"></a><span class="co"># Factorial observations receive a Block x Irrigation whole plot label.</span></span>
<span id="cb2-78"><a href="#cb2-78" aria-hidden="true" tabindex="-1"></a><span class="co"># Control observations receive a separate control label.</span></span>
<span id="cb2-79"><a href="#cb2-79" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>WholePlot <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(</span>
<span id="cb2-80"><a href="#cb2-80" aria-hidden="true" tabindex="-1"></a>  splt_df<span class="sc">$</span>Control <span class="sc">==</span> <span class="st">"n"</span>,</span>
<span id="cb2-81"><a href="#cb2-81" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste</span>(splt_df<span class="sc">$</span>Block, splt_df<span class="sc">$</span>Irrigation, <span class="at">sep =</span> <span class="st">"_"</span>),</span>
<span id="cb2-82"><a href="#cb2-82" aria-hidden="true" tabindex="-1"></a>  <span class="fu">paste</span>(splt_df<span class="sc">$</span>Block, <span class="st">"Control"</span>, <span class="at">sep =</span> <span class="st">"_"</span>)</span>
<span id="cb2-83"><a href="#cb2-83" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-84"><a href="#cb2-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-85"><a href="#cb2-85" aria-hidden="true" tabindex="-1"></a><span class="co"># Merge the whole plot effects into the main data set.</span></span>
<span id="cb2-86"><a href="#cb2-86" aria-hidden="true" tabindex="-1"></a><span class="co"># Only factorial observations receive whole plot effects.</span></span>
<span id="cb2-87"><a href="#cb2-87" aria-hidden="true" tabindex="-1"></a>splt_df <span class="ot">&lt;-</span> splt_df <span class="sc">%&gt;%</span></span>
<span id="cb2-88"><a href="#cb2-88" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(</span>
<span id="cb2-89"><a href="#cb2-89" aria-hidden="true" tabindex="-1"></a>    whole_plot_units[, <span class="fu">c</span>(<span class="st">"WholePlot"</span>, <span class="st">"WholePlotEffect"</span>)],</span>
<span id="cb2-90"><a href="#cb2-90" aria-hidden="true" tabindex="-1"></a>    <span class="at">by =</span> <span class="st">"WholePlot"</span></span>
<span id="cb2-91"><a href="#cb2-91" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-92"><a href="#cb2-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-93"><a href="#cb2-93" aria-hidden="true" tabindex="-1"></a><span class="co"># Since the control is outside the factorial whole plot structure,</span></span>
<span id="cb2-94"><a href="#cb2-94" aria-hidden="true" tabindex="-1"></a><span class="co"># it does not receive an irrigation whole plot effect.</span></span>
<span id="cb2-95"><a href="#cb2-95" aria-hidden="true" tabindex="-1"></a><span class="co"># Missing whole plot effects for the control are set to zero.</span></span>
<span id="cb2-96"><a href="#cb2-96" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>WholePlotEffect[<span class="fu">is.na</span>(splt_df<span class="sc">$</span>WholePlotEffect)] <span class="ot">&lt;-</span> <span class="dv">0</span></span>
<span id="cb2-97"><a href="#cb2-97" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-98"><a href="#cb2-98" aria-hidden="true" tabindex="-1"></a><span class="co"># Simulate corn yield.</span></span>
<span id="cb2-99"><a href="#cb2-99" aria-hidden="true" tabindex="-1"></a><span class="co"># The value 100 is the baseline yield.</span></span>
<span id="cb2-100"><a href="#cb2-100" aria-hidden="true" tabindex="-1"></a><span class="co"># Block effects represent differences among blocks.</span></span>
<span id="cb2-101"><a href="#cb2-101" aria-hidden="true" tabindex="-1"></a><span class="co"># Irrigation and weed effects are added only for factorial treatments.</span></span>
<span id="cb2-102"><a href="#cb2-102" aria-hidden="true" tabindex="-1"></a><span class="co"># The control receives its own separate effect.</span></span>
<span id="cb2-103"><a href="#cb2-103" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Yield <span class="ot">&lt;-</span> <span class="fu">with</span>(</span>
<span id="cb2-104"><a href="#cb2-104" aria-hidden="true" tabindex="-1"></a>  splt_df,</span>
<span id="cb2-105"><a href="#cb2-105" aria-hidden="true" tabindex="-1"></a>  <span class="dv">100</span> <span class="sc">+</span></span>
<span id="cb2-106"><a href="#cb2-106" aria-hidden="true" tabindex="-1"></a>    block_effects[<span class="fu">as.numeric</span>(Block)] <span class="sc">+</span></span>
<span id="cb2-107"><a href="#cb2-107" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Irrigation <span class="sc">==</span> <span class="st">"Drip"</span>, <span class="dv">8</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb2-108"><a href="#cb2-108" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Irrigation <span class="sc">==</span> <span class="st">"Sprinkler"</span>, <span class="dv">4</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb2-109"><a href="#cb2-109" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Weed <span class="sc">==</span> <span class="st">"Herbicide A"</span>, <span class="dv">10</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb2-110"><a href="#cb2-110" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Weed <span class="sc">==</span> <span class="st">"Herbicide B"</span>, <span class="dv">14</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb2-111"><a href="#cb2-111" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Irrigation <span class="sc">==</span> <span class="st">"Drip"</span> <span class="sc">&amp;</span> Weed <span class="sc">==</span> <span class="st">"Herbicide B"</span>, <span class="dv">4</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb2-112"><a href="#cb2-112" aria-hidden="true" tabindex="-1"></a>    <span class="fu">ifelse</span>(Control <span class="sc">==</span> <span class="st">"y"</span>, <span class="sc">-</span><span class="dv">6</span>, <span class="dv">0</span>) <span class="sc">+</span></span>
<span id="cb2-113"><a href="#cb2-113" aria-hidden="true" tabindex="-1"></a>    WholePlotEffect <span class="sc">+</span></span>
<span id="cb2-114"><a href="#cb2-114" aria-hidden="true" tabindex="-1"></a>    <span class="fu">rnorm</span>(<span class="fu">nrow</span>(splt_df), <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="dv">3</span>)</span>
<span id="cb2-115"><a href="#cb2-115" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-116"><a href="#cb2-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-117"><a href="#cb2-117" aria-hidden="true" tabindex="-1"></a><span class="co"># Round the simulated yield values to two decimal places.</span></span>
<span id="cb2-118"><a href="#cb2-118" aria-hidden="true" tabindex="-1"></a>splt_df<span class="sc">$</span>Yield <span class="ot">&lt;-</span> <span class="fu">round</span>(splt_df<span class="sc">$</span>Yield, <span class="dv">2</span>)</span>
<span id="cb2-119"><a href="#cb2-119" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-120"><a href="#cb2-120" aria-hidden="true" tabindex="-1"></a><span class="co"># Display the simulated data in a table.</span></span>
<span id="cb2-121"><a href="#cb2-121" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb2-122"><a href="#cb2-122" aria-hidden="true" tabindex="-1"></a>  splt_df[, <span class="fu">c</span>(<span class="st">"Block"</span>, <span class="st">"Irrigation"</span>, <span class="st">"Weed"</span>, <span class="st">"Control"</span>, <span class="st">"Yield"</span>)],</span>
<span id="cb2-123"><a href="#cb2-123" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Simulated Corn Yield Data for a Split-Plot Design With Control as an Extra Treatment"</span>,</span>
<span id="cb2-124"><a href="#cb2-124" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(</span>
<span id="cb2-125"><a href="#cb2-125" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Block"</span>,</span>
<span id="cb2-126"><a href="#cb2-126" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Irrigation Method"</span>,</span>
<span id="cb2-127"><a href="#cb2-127" aria-hidden="true" tabindex="-1"></a>    <span class="st">"weed Treatment"</span>,</span>
<span id="cb2-128"><a href="#cb2-128" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Control"</span>,</span>
<span id="cb2-129"><a href="#cb2-129" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Corn Yield"</span></span>
<span id="cb2-130"><a href="#cb2-130" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb2-131"><a href="#cb2-131" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Simulated Corn Yield Data for a Split-Plot Design With Control as an Extra Treatment</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Block</th>
<th style="text-align: left;">Irrigation Method</th>
<th style="text-align: left;">weed Treatment</th>
<th style="text-align: left;">Control</th>
<th style="text-align: right;">Corn Yield</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">115.46</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">112.69</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">117.91</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">115.75</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">109.93</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">110.14</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">115.56</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">114.73</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">112.11</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">117.88</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">115.12</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">109.77</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">124.29</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">119.12</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">126.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">125.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">122.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">117.24</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">121.20</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">110.33</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">112.65</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">119.23</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">113.71</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">110.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">92.47</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">90.60</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">92.06</td>
</tr>
<tr class="even">
<td style="text-align: left;">4</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">97.92</td>
</tr>
<tr class="odd">
<td style="text-align: left;">5</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">93.47</td>
</tr>
<tr class="even">
<td style="text-align: left;">6</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">82.73</td>
</tr>
</tbody>
</table>
<p></p>
</div>
</div>
</section>
<section id="histogram-of-corn-yield" class="level3">
<h3 class="anchored" data-anchor-id="histogram-of-corn-yield">Histogram of Corn Yield</h3>
<p>The histogram provides an overall view of how the corn yield values are spread across the study, allowing for a quick assessment of the center, variability, and general shape of the simulated response distribution before comparing treatment combinations more specifically.</p>
<p>Figure 1 shows the distribution of corn yield values in the simulated data. Most observations are concentrated between approximately 110 and 120, indicating that the majority of corn yield measurements fall within this higher-yield range. The distribution is not perfectly symmetrical, as a few lower-yield observations appear between about 80 and 98, creating a slight left-skewed pattern. Overall, the histogram suggests that corn yield is generally clustered around the mid-110s, with only a small number of observations showing noticeably lower yield values.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Histogram of corn yield</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(splt_df, <span class="fu">aes</span>(<span class="at">x =</span> Yield)) <span class="sc">+</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins =</span> <span class="dv">10</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">fill =</span> <span class="st">"gray"</span>) <span class="sc">+</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Histogram Showing the Distribution of Corn Yield"</span>,</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Corn Yield"</span>,</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Frequency"</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="split_plot_irrigation_weed_control_R_files/figure-html/histogram-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Distribution of Corn Yield</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="boxplot-of-corn-yield-and-treatments" class="level3">
<h3 class="anchored" data-anchor-id="boxplot-of-corn-yield-and-treatments">Boxplot of Corn Yield and Treatments</h3>
<p>In this study, the boxplot helps compare corn yield values across treatment groups and control, making it easier to identify differences in central tendency, variability, and unusual observations among the groups.</p>
<p>Figure 2 compares corn yield across the control and four treatment conditions. The control group shows the lowest median yield, with most values clustered around the low 90s and two visible outliers. In contrast, all treatment combinations produced higher corn yields than the control. Among the treatments, Drip + Herbicide B had the highest median yield, with values centered in the low-to-mid 120s, suggesting the strongest yield performance. Drip + Herbicide A, Sprinkler + Herbicide A, and Sprinkler + Herbicide B showed similar median yields in the low-to-mid 110s, although Sprinkler + Herbicide B displayed slightly greater variability. Overall, the boxplot suggests that the treatment conditions improved corn yield compared with the control.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co">#---------------------------------------------------------#</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The boxplot then compares corn yield across the five treatment conditions: the control and the four factorial treatment combinations. This is more appropriate than using `facet_wrap(~ Irrigation)` because the control has no irrigation level.</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>splt_df_plot <span class="ot">&lt;-</span> splt_df <span class="sc">%&gt;%</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>    <span class="at">Treatment =</span> <span class="fu">ifelse</span>(</span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>      Control <span class="sc">==</span> <span class="st">"y"</span>,</span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>      <span class="st">"Control"</span>,</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>      <span class="fu">paste</span>(Irrigation, Weed, <span class="at">sep =</span> <span class="st">" + "</span>)</span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert Treatment to a factor </span></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a>splt_df_plot<span class="sc">$</span>Treatment <span class="ot">&lt;-</span> <span class="fu">factor</span>(</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a>  splt_df_plot<span class="sc">$</span>Treatment,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">levels =</span> <span class="fu">c</span>(</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Control"</span>,</span>
<span id="cb4-19"><a href="#cb4-19" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Drip + Herbicide A"</span>,</span>
<span id="cb4-20"><a href="#cb4-20" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Drip + Herbicide B"</span>,</span>
<span id="cb4-21"><a href="#cb4-21" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sprinkler + Herbicide A"</span>,</span>
<span id="cb4-22"><a href="#cb4-22" aria-hidden="true" tabindex="-1"></a>    <span class="st">"Sprinkler + Herbicide B"</span></span>
<span id="cb4-23"><a href="#cb4-23" aria-hidden="true" tabindex="-1"></a>  )</span>
<span id="cb4-24"><a href="#cb4-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb4-25"><a href="#cb4-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-26"><a href="#cb4-26" aria-hidden="true" tabindex="-1"></a><span class="co"># Boxplot of corn yield by treatment condition</span></span>
<span id="cb4-27"><a href="#cb4-27" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(splt_df_plot, <span class="fu">aes</span>(<span class="at">x =</span> Treatment, <span class="at">y =</span> Yield, <span class="at">fill =</span> Treatment)) <span class="sc">+</span></span>
<span id="cb4-28"><a href="#cb4-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb4-29"><a href="#cb4-29" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb4-30"><a href="#cb4-30" aria-hidden="true" tabindex="-1"></a>    <span class="at">title =</span> <span class="st">"Boxplot of Corn Yield by Treatment Condition"</span>,</span>
<span id="cb4-31"><a href="#cb4-31" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Treatment Condition"</span>,</span>
<span id="cb4-32"><a href="#cb4-32" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Corn Yield"</span></span>
<span id="cb4-33"><a href="#cb4-33" aria-hidden="true" tabindex="-1"></a>  ) <span class="sc">+</span></span>
<span id="cb4-34"><a href="#cb4-34" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb4-35"><a href="#cb4-35" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(</span>
<span id="cb4-36"><a href="#cb4-36" aria-hidden="true" tabindex="-1"></a>    <span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">45</span>, <span class="at">hjust =</span> <span class="dv">1</span>),</span>
<span id="cb4-37"><a href="#cb4-37" aria-hidden="true" tabindex="-1"></a>    <span class="at">legend.position =</span> <span class="st">"none"</span></span>
<span id="cb4-38"><a href="#cb4-38" aria-hidden="true" tabindex="-1"></a>  )</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="split_plot_irrigation_weed_control_R_files/figure-html/boxplot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Corn Yield for Factorial Treatment Combinations and Control</figcaption>
</figure>
</div>
</div>
</div>
</section>
<section id="interaction-plot" class="level3">
<h3 class="anchored" data-anchor-id="interaction-plot">Interaction Plot</h3>
<p>As stated in the previous chapter, an interaction plot is important in a factorial design because it helps determine whether the effect of one factor depends on the level of another factor. While main effects show the overall influence of each factor separately, an interaction plot shows whether treatment combinations behave differently when factors are considered together.</p>
<p>Figure 3 shows the interaction plot between irrigation method and weed treatment. If the lines in the interaction plot are not parallel or appear to cross, this suggests that an interaction may be present. In this study, the interaction plot helps evaluate whether the effect of herbicide type on corn yield changes depending on the irrigation method used. The horizontal dashed line represents the average corn yield for the control treatment. This allows the reader to visually compare the factorial treatment combinations with the control without incorrectly treating the control as part of the factorial structure.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Remove the control group before making the interaction plot.</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------------------#</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>splt_df_factorial <span class="ot">&lt;-</span> splt_df <span class="sc">%&gt;%</span></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Control <span class="sc">==</span> <span class="st">"n"</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------------------#</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate the mean yield for the control group.</span></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="co"># This will be added to the plot as a reference line.</span></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------------------------------------------#</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>control_mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(splt_df<span class="sc">$</span>Yield[splt_df<span class="sc">$</span>Control <span class="sc">==</span> <span class="st">"y"</span>])</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Interaction plot for the factorial treatment combinations only.</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">x.factor =</span> splt_df_factorial<span class="sc">$</span>Weed,</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace.factor =</span> splt_df_factorial<span class="sc">$</span>Irrigation,</span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">response =</span> splt_df_factorial<span class="sc">$</span>Yield,</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">type =</span> <span class="st">"b"</span>,</span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">pch =</span> <span class="dv">16</span>,</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"weed Treatment"</span>,</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Average Corn Yield"</span>,</span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace.label =</span> <span class="st">"Irrigation"</span>,</span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>  <span class="at">main =</span> <span class="st">"Interaction Plot of Irrigation and weed Treatment</span><span class="sc">\n</span><span class="st">With Control Reference"</span></span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a horizontal line for the control mean.</span></span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="co"># This shows the average yield for the control treatment.</span></span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="fu">abline</span>(</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>  <span class="at">h =</span> control_mean,</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="dv">2</span>,</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span></span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-35"><a href="#cb5-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-36"><a href="#cb5-36" aria-hidden="true" tabindex="-1"></a><span class="co"># Add a legend to identify the control mean line.</span></span>
<span id="cb5-37"><a href="#cb5-37" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(</span>
<span id="cb5-38"><a href="#cb5-38" aria-hidden="true" tabindex="-1"></a>  <span class="st">"topleft"</span>,</span>
<span id="cb5-39"><a href="#cb5-39" aria-hidden="true" tabindex="-1"></a>  <span class="at">legend =</span> <span class="st">"Control Mean"</span>,</span>
<span id="cb5-40"><a href="#cb5-40" aria-hidden="true" tabindex="-1"></a>  <span class="at">lty =</span> <span class="dv">2</span>,</span>
<span id="cb5-41"><a href="#cb5-41" aria-hidden="true" tabindex="-1"></a>  <span class="at">lwd =</span> <span class="dv">2</span>,</span>
<span id="cb5-42"><a href="#cb5-42" aria-hidden="true" tabindex="-1"></a>  <span class="at">bty =</span> <span class="st">"n"</span></span>
<span id="cb5-43"><a href="#cb5-43" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="split_plot_irrigation_weed_control_R_files/figure-html/interaction-plot-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption class="figure-caption">Interaction Plot of Irrigation Method and weed Treatment With Control Reference</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="advanced-analysis" class="level2">
<h2 class="anchored" data-anchor-id="advanced-analysis">Advanced Analysis</h2>
<p>The objective of the analysis is to determine whether corn yield differs by irrigation method, weed treatment, and the irrigation by weed interaction among the factorial treatment combinations. In addition, the analysis determines whether the factorial treatments differ from the control treatment.</p>
<p>Because the design is a split-plot design, the analysis must account for the random block effect and the random whole plot error. The whole plot factor is irrigation method, and it is randomized to whole plots within each block. The split plot factor is weed treatment, and it is randomized to subplots within each irrigation whole plot.</p>
<p>In this example, block and whole plot are treated as random effects. Irrigation method and weed treatment are treated as fixed effects within the factorial portion of the design. The control treatment is not part of the irrigation-by-weed factorial structure. Therefore, the control is modeled separately using a control indicator variable.</p>
<p>The whole plot error is represented by the random whole plot term nested within block and irrigation. This error term is important because irrigation is applied at the whole plot level. The subplot error is used to evaluate the weed effect and the irrigation by weed interaction. The control treatment is included as an extra treatment so that the average response of the factorial treatments can be compared with the control.</p>
</section>
<section id="statistical-model" class="level2">
<h2 class="anchored" data-anchor-id="statistical-model">Statistical Model</h2>
<p>The statistical model for the split-plot design with a control as an extra treatment is given as</p>
<p><span class="math display">\[
Y_{ijk\ell} = \mu + b_k + \alpha_i + w_{ik} + \beta_j + (\alpha\beta)_{ij} + \gamma I_{\ell} + \epsilon_{ijk\ell},
\]</span></p>
<p>and</p>
<p><span class="math display">\[
I_{\ell} =
\begin{cases}
1, &amp; \text{if the observation belongs to the control treatment},\
0, &amp; \text{if the observation belongs to one of the factorial treatments}.
\end{cases}
\]</span></p>
<p>where:</p>
<ul>
<li><span class="math inline">\(Y_{ijk\ell}\)</span> is the corn yield response for the experimental unit receiving the <span class="math inline">\(i\)</span>th irrigation method and the <span class="math inline">\(j\)</span>th weed treatment in the <span class="math inline">\(k\)</span>th block;</li>
<li><span class="math inline">\(\mu\)</span> is the baseline mean for the factorial treatment combinations;</li>
<li><span class="math inline">\(b_k\)</span> is the random effect of the <span class="math inline">\(k\)</span>th block;</li>
<li><span class="math inline">\(\alpha_i\)</span> is the fixed effect of the <span class="math inline">\(i\)</span>th irrigation method;</li>
<li><span class="math inline">\(w_{ik}\)</span> is the random whole plot error associated with the <span class="math inline">\(i\)</span>th irrigation whole plot within the <span class="math inline">\(k\)</span>th block;</li>
<li><span class="math inline">\(\beta_j\)</span> is the fixed effect of the <span class="math inline">\(j\)</span>th weed treatment;</li>
<li><span class="math inline">\((\alpha\beta)_{ij}\)</span> is the fixed interaction effect between irrigation method and weed treatment;</li>
<li><span class="math inline">\(\gamma\)</span> measures the difference between the control treatment and the factorial treatment baseline;</li>
<li><span class="math inline">\(I_{\ell}\)</span> is the control indicator variable;</li>
<li><span class="math inline">\(\epsilon_{ijk\ell}\)</span> is the subplot error term.</li>
</ul>
<p>The terms <span class="math inline">\(\alpha_i\)</span>, <span class="math inline">\(\beta_j\)</span>, and <span class="math inline">\((\alpha\beta)_{ij}\)</span> are estimated using only the factorial treatment combinations. This is because the control does not have an irrigation method or active weed treatment. Therefore, the control does not contribute to the estimation of the irrigation main effect, the weed main effect, or the irrigation by weed interaction.</p>
<p>The control term, <span class="math inline">\(\gamma I_{\ell}\)</span>, allows the model to compare the control treatment with the factorial treatments without incorrectly forcing the control into the factorial structure. This preserves the correct interpretation of the control as a separate baseline treatment.</p>
<p>The model assumes that the random block effects, whole plot errors, and subplot errors are independently and normally distributed with mean zero and constant variances. Specifically,</p>
<p><span class="math display">\[
b_k \sim N(0, \sigma_b^2),
\]</span></p>
<p><span class="math display">\[
w_{ik} \sim N(0, \sigma_w^2),
\]</span></p>
<p>and</p>
<p><span class="math display">\[
\epsilon_{ijk\ell} \sim N(0, \sigma^2).
\]</span></p>
<p>No block-by-treatment interaction is assumed in this model.</p>
<section id="covariance-parameter-estimates" class="level3">
<h3 class="anchored" data-anchor-id="covariance-parameter-estimates">Covariance Parameter Estimates</h3>
<p>The model summary provides fixed-effect estimates and variance components. Nevertheless, we only show the covariance parameter estimates for block, block by irrigation and residual. The variance component for <code>Block:Irrigation</code> represents the whole plot error. The residual variance represents the subplot error.</p>
<p>From Table 3, the estimated variance for <code>Block:Irrigation</code> is <span class="math inline">\(2.34\)</span>, and <span class="math inline">\(9.38\)</span> for <code>Block</code>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------------------#</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit the split-plot mixed model</span></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------------------------------------------#</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>split_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a>  Yield <span class="sc">~</span> Control <span class="sc">+</span> Irrigation<span class="sc">:</span>Control <span class="sc">+</span> Weed<span class="sc">:</span>Control <span class="sc">+</span></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    Irrigation<span class="sc">:</span>Weed<span class="sc">:</span>Control <span class="sc">+</span></span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> Block) <span class="sc">+</span></span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> Block<span class="sc">:</span>Irrigation),</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> splt_df,</span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">TRUE</span></span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Get estimates for variance components</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>cov_parm_split <span class="ot">&lt;-</span> <span class="fu">VarCorr</span>(split_model)</span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>cov_parm_split <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(cov_parm_split)</span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>cov_parm_split<span class="sc">$</span>var2 <span class="ot">&lt;-</span> <span class="cn">NULL</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a>  cov_parm_split,</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Covariance parameter estimate"</span>,</span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>  <span class="at">col.names =</span> <span class="fu">c</span>(<span class="st">"Group"</span>, <span class="st">"Name"</span>, <span class="st">"Variance"</span>, <span class="st">"SdCor"</span>)</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Covariance parameter estimate</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Group</th>
<th style="text-align: left;">Name</th>
<th style="text-align: right;">Variance</th>
<th style="text-align: right;">SdCor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Block:Irrigation</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">2.340104</td>
<td style="text-align: right;">1.529740</td>
</tr>
<tr class="even">
<td style="text-align: left;">Block</td>
<td style="text-align: left;">(Intercept)</td>
<td style="text-align: right;">9.376770</td>
<td style="text-align: right;">3.062151</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Residual</td>
<td style="text-align: left;">NA</td>
<td style="text-align: right;">4.139071</td>
<td style="text-align: right;">2.034471</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="anova-table" class="level3">
<h3 class="anchored" data-anchor-id="anova-table">ANOVA Table</h3>
<p>Table 4 shows the ANOVA table for the split-plot mixed model. The irrigation effect is evaluated using the whole plot structure, while the weed effect and the irrigation by weed interaction are evaluated using the subplot structure.</p>
<p>From Table 4, all factors are statistically significant including the control. The p-values are all less than <span class="math inline">\(0.05\)</span>. With this simulated data, it means that for each factor, the factor levels differ in effect on corn yield from each other. Also, at least one of the treatment factors differ from the control group.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------------------#</span></span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a><span class="co"># ANOVA table using Kenward-Roger degrees of freedom</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a><span class="co"># The model accounts for the split-plot structure and the separate control treatment.</span></span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------------------------------------------#</span></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a>anova_split <span class="ot">&lt;-</span> <span class="fu">anova</span>(</span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>  split_model,</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">ddf =</span> <span class="st">"Kenward-Roger"</span></span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>  anova_split,</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"ANOVA Table for the Split-Plot Mixed Model With Control as an Extra Treatment"</span></span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>ANOVA Table for the Split-Plot Mixed Model With Control as an Extra Treatment</caption>
<colgroup>
<col style="width: 29%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 7%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Sum Sq</th>
<th style="text-align: right;">Mean Sq</th>
<th style="text-align: right;">NumDF</th>
<th style="text-align: right;">DenDF</th>
<th style="text-align: right;">F value</th>
<th style="text-align: right;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Control</td>
<td style="text-align: right;">936.45181</td>
<td style="text-align: right;">936.45181</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">15.566384</td>
<td style="text-align: right;">226.246869</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control:Irrigation</td>
<td style="text-align: right;">36.74826</td>
<td style="text-align: right;">36.74826</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">7.854778</td>
<td style="text-align: right;">8.878383</td>
<td style="text-align: right;">0.0179776</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Control:Weed</td>
<td style="text-align: right;">129.13120</td>
<td style="text-align: right;">129.13120</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.215434</td>
<td style="text-align: right;">31.198114</td>
<td style="text-align: right;">0.0002149</td>
</tr>
<tr class="even">
<td style="text-align: left;">Control:Irrigation:Weed</td>
<td style="text-align: right;">103.87520</td>
<td style="text-align: right;">103.87520</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">10.215434</td>
<td style="text-align: right;">25.096262</td>
<td style="text-align: right;">0.0004965</td>
</tr>
</tbody>
</table>
<p></p>
</div>
</div>
</section>
<section id="estimated-marginal-means-for-each-irrigation-by-weed-treatment-combination" class="level3">
<h3 class="anchored" data-anchor-id="estimated-marginal-means-for-each-irrigation-by-weed-treatment-combination">Estimated Marginal Means for each Irrigation-by-Weed Treatment Combination</h3>
<p>Table 5 shows the estimated marginal means for the factorial treatment combinations only. These treatment combinations are drip irrigation with herbicide A, drip irrigation with herbicide B, sprinkler irrigation with herbicide A, and sprinkler irrigation with herbicide B.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># within the factorial portion of the design.</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>emm_treatments <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  split_model,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Irrigation <span class="sc">*</span> Weed <span class="sc">|</span> Control</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert estimated marginal means to a data frame</span></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>emm_treatments_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(emm_treatments)</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only the factorial treatment combinations</span></span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Control == "n" means the observation belongs to the factorial portion.</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>emm_treatments_factorial <span class="ot">&lt;-</span> emm_treatments_df <span class="sc">%&gt;%</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Control <span class="sc">==</span> <span class="st">"n"</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  emm_treatments_factorial,</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Estimated Marginal Means for the Factorial Irrigation by Weed-Control Treatment Combinations"</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means for the Factorial Irrigation by Weed-Control Treatment Combinations</caption>
<colgroup>
<col style="width: 14%">
<col style="width: 15%">
<col style="width: 10%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 11%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Irrigation</th>
<th style="text-align: left;">Weed</th>
<th style="text-align: left;">Control</th>
<th style="text-align: right;">emmean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">lower.CL</th>
<th style="text-align: right;">upper.CL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">113.6467</td>
<td style="text-align: right;">1.625625</td>
<td style="text-align: right;">9.816736</td>
<td style="text-align: right;">110.0154</td>
<td style="text-align: right;">117.2780</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">114.1950</td>
<td style="text-align: right;">1.625625</td>
<td style="text-align: right;">9.816736</td>
<td style="text-align: right;">110.5637</td>
<td style="text-align: right;">117.8263</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">122.4467</td>
<td style="text-align: right;">1.625625</td>
<td style="text-align: right;">9.816736</td>
<td style="text-align: right;">118.8154</td>
<td style="text-align: right;">126.0780</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">114.6733</td>
<td style="text-align: right;">1.625625</td>
<td style="text-align: right;">9.816736</td>
<td style="text-align: right;">111.0420</td>
<td style="text-align: right;">118.3046</td>
</tr>
</tbody>
</table>
<p></p>
</div>
</div>
</section>
<section id="main-effects-for-weed-treatments" class="level3">
<h3 class="anchored" data-anchor-id="main-effects-for-weed-treatments">Main Effects for Weed Treatments</h3>
<p>Table 6 shows the estimated marginal means for the active weed treatments averaged over irrigation method. This table only compares herbicide A and herbicide B within the factorial portion of the design. These means are useful for understanding whether the two active weed treatments differ in their average effect on corn yield.</p>
<p>From Table 6, the estimated marginal means of corn yield for Herbicides A and B are <span class="math inline">\(113.92\)</span> and <span class="math inline">\(118.56\)</span> respectively.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co">#----------------------------------------------------#</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated marginal means for weed-control treatment</span></span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a><span class="co"># averaged over irrigation within the factorial portion of the design.</span></span>
<span id="cb9-4"><a href="#cb9-4" aria-hidden="true" tabindex="-1"></a><span class="co">#---------------------------------------------------#</span></span>
<span id="cb9-5"><a href="#cb9-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-6"><a href="#cb9-6" aria-hidden="true" tabindex="-1"></a>emm_weed <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(</span>
<span id="cb9-7"><a href="#cb9-7" aria-hidden="true" tabindex="-1"></a>  split_model,</span>
<span id="cb9-8"><a href="#cb9-8" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Weed <span class="sc">|</span> Control</span>
<span id="cb9-9"><a href="#cb9-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb9-10"><a href="#cb9-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-11"><a href="#cb9-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Convert estimated marginal means to a data frame</span></span>
<span id="cb9-12"><a href="#cb9-12" aria-hidden="true" tabindex="-1"></a>emm_weed_df <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(emm_weed)</span>
<span id="cb9-13"><a href="#cb9-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-14"><a href="#cb9-14" aria-hidden="true" tabindex="-1"></a><span class="co"># Keep only the factorial treatment portion</span></span>
<span id="cb9-15"><a href="#cb9-15" aria-hidden="true" tabindex="-1"></a>emm_weed_factorial <span class="ot">&lt;-</span> emm_weed_df <span class="sc">%&gt;%</span></span>
<span id="cb9-16"><a href="#cb9-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Control <span class="sc">==</span> <span class="st">"n"</span>)</span>
<span id="cb9-17"><a href="#cb9-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb9-18"><a href="#cb9-18" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb9-19"><a href="#cb9-19" aria-hidden="true" tabindex="-1"></a>  emm_weed_factorial,</span>
<span id="cb9-20"><a href="#cb9-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Estimated Marginal Means for Weed-Control Treatment Within the Factorial Portion of the Design"</span></span>
<span id="cb9-21"><a href="#cb9-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means for Weed-Control Treatment Within the Factorial Portion of the Design</caption>
<colgroup>
<col style="width: 18%">
<col style="width: 12%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Weed</th>
<th style="text-align: left;">Control</th>
<th style="text-align: right;">emmean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">lower.CL</th>
<th style="text-align: right;">upper.CL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">113.9208</td>
<td style="text-align: right;">1.450078</td>
<td style="text-align: right;">6.517277</td>
<td style="text-align: right;">110.4398</td>
<td style="text-align: right;">117.4019</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">118.5600</td>
<td style="text-align: right;">1.450078</td>
<td style="text-align: right;">6.517277</td>
<td style="text-align: right;">115.0789</td>
<td style="text-align: right;">122.0411</td>
</tr>
</tbody>
</table>
<p></p>
</div>
</div>
</section>
<section id="main-effects-of-treatments-and-control" class="level3">
<h3 class="anchored" data-anchor-id="main-effects-of-treatments-and-control">Main Effects of Treatments and Control</h3>
<p>With experiments involving a control like the example considered here, researchers may also be interested in comparing the main effects of treatments with the control. Table 6 shows the estimated marginal means for the factorial treatments and the control treatment. The level <code>n</code> represents the average response for the factorial treatment combinations. The level <code>y</code> represents the average response for the control treatment. The estimated mean over all treatments was <span class="math inline">\(116.24\)</span> and that of the control was <span class="math inline">\(91.54\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated marginal means for the control indicator</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Control = "n" represents the average of the factorial treatments.</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Control = "y" represents the extra control treatment.</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>emm_control <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(</span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>  split_model,</span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Control</span>
<span id="cb10-7"><a href="#cb10-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb10-8"><a href="#cb10-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb10-9"><a href="#cb10-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb10-10"><a href="#cb10-10" aria-hidden="true" tabindex="-1"></a>  emm_control,</span>
<span id="cb10-11"><a href="#cb10-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Estimated Marginal Means for Factorial Treatments and Control"</span></span>
<span id="cb10-12"><a href="#cb10-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means for Factorial Treatments and Control</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Control</th>
<th style="text-align: right;">emmean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">lower.CL</th>
<th style="text-align: right;">upper.CL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n</td>
<td style="text-align: right;">116.24042</td>
<td style="text-align: right;">1.389340</td>
<td style="text-align: right;">5.506080</td>
<td style="text-align: right;">112.76552</td>
<td style="text-align: right;">119.71532</td>
</tr>
<tr class="even">
<td style="text-align: left;">y</td>
<td style="text-align: right;">91.54167</td>
<td style="text-align: right;">1.625625</td>
<td style="text-align: right;">9.816736</td>
<td style="text-align: right;">87.91036</td>
<td style="text-align: right;">95.17297</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="difference-of-main-effect-between-treatment-and-control" class="level3">
<h3 class="anchored" data-anchor-id="difference-of-main-effect-between-treatment-and-control">Difference of Main Effect Between Treatment and Control</h3>
<p>Table 8 compares the average of the factorial treatment combinations with the control treatment. This comparison answers whether receiving one of the irrigation-by-weed treatment combinations leads to a different average corn yield than receiving the control treatment.</p>
<p>Dunnett adjustment is not used here because this specific comparison involves only two groups: the average of the factorial treatments and the control treatment. Dunnett adjustment is more useful when several treatment groups are each being compared with the same control. From Table 8, the estimated difference in corn yield between treatments and the control is <span class="math inline">\(24.69\)</span> with p-value of <span class="math inline">\(0\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare the average of the factorial treatments with the control treatment.</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>factorial_vs_control <span class="ot">&lt;-</span> <span class="fu">contrast</span>(</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>  emm_control,</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"pairwise"</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>  factorial_vs_control,</span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Comparison of Factorial Treatments Against the Control Treatment"</span></span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Comparison of Factorial Treatments Against the Control Treatment</caption>
<thead>
<tr class="header">
<th style="text-align: left;">contrast</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">t.ratio</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">n - y</td>
<td style="text-align: right;">24.69875</td>
<td style="text-align: right;">1.203051</td>
<td style="text-align: right;">13.24812</td>
<td style="text-align: right;">20.53009</td>
<td style="text-align: right;">0</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="simple-effects" class="level2">
<h2 class="anchored" data-anchor-id="simple-effects">Simple Effects</h2>
<p>Simple effects are useful when the interaction between irrigation method and weed treatment is statistically significant. A simple effect examines the effect of one factor at a given level of another factor. In this example, simple effects can be used to compare the active weed treatments within each irrigation method. Nevertheless, the control does not belong to a specific irrigation method or active weed treatment. Therefore, it would not be compared as though it were one of the weed levels within drip or sprinkler irrigation.</p>
<p>A split-plot mixed model fitted to the factorial portion of the data. This model is used to examine the simple effects of weed treatment and irrigation method.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co">#---------------------------------------------------------#</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Create a data set containing only the factorial treatment combinations</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#--------------------------------------------------------#</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>df_factorial <span class="ot">&lt;-</span> splt_df <span class="sc">%&gt;%</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(Control <span class="sc">==</span> <span class="st">"n"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># This model is used for simple effects of irrigation and weed-control treatment</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a>factorial_model <span class="ot">&lt;-</span> <span class="fu">lmer</span>(</span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a>  Yield <span class="sc">~</span> Irrigation <span class="sc">*</span> Weed <span class="sc">+</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> Block) <span class="sc">+</span></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a>    (<span class="dv">1</span> <span class="sc">|</span> Block<span class="sc">:</span>Irrigation),</span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">data =</span> df_factorial,</span>
<span id="cb12-17"><a href="#cb12-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">REML =</span> <span class="cn">TRUE</span></span>
<span id="cb12-18"><a href="#cb12-18" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-19"><a href="#cb12-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-20"><a href="#cb12-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple effects of weed-control treatment within each irrigation method</span></span>
<span id="cb12-21"><a href="#cb12-21" aria-hidden="true" tabindex="-1"></a>emm_weed_by_irrigation <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(</span>
<span id="cb12-22"><a href="#cb12-22" aria-hidden="true" tabindex="-1"></a>  factorial_model,</span>
<span id="cb12-23"><a href="#cb12-23" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Weed <span class="sc">|</span> Irrigation</span>
<span id="cb12-24"><a href="#cb12-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb12-25"><a href="#cb12-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-26"><a href="#cb12-26" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb12-27"><a href="#cb12-27" aria-hidden="true" tabindex="-1"></a>  emm_weed_by_irrigation,</span>
<span id="cb12-28"><a href="#cb12-28" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Simple Effects of Weed-Control Treatment Within Each Irrigation Method"</span></span>
<span id="cb12-29"><a href="#cb12-29" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Simple Effects of Weed-Control Treatment Within Each Irrigation Method</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Weed</th>
<th style="text-align: left;">Irrigation</th>
<th style="text-align: right;">emmean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">lower.CL</th>
<th style="text-align: right;">upper.CL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: right;">113.6467</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">110.3943</td>
<td style="text-align: right;">116.8991</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: right;">122.4467</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">119.1943</td>
<td style="text-align: right;">125.6991</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: right;">114.1950</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">110.9426</td>
<td style="text-align: right;">117.4474</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: right;">114.6733</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">111.4209</td>
<td style="text-align: right;">117.9257</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Table 9 gives the estimated marginal means for the active weed treatments separately within each irrigation method. Since the control is not part of the factorial structure, only herbicide A and herbicide B are shown within drip and sprinkler irrigation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare herbicide A and herbicide B within each irrigation method</span></span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>weed_contrasts_by_irrigation <span class="ot">&lt;-</span> <span class="fu">contrast</span>(</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a>  emm_weed_by_irrigation,</span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"pairwise"</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>  weed_contrasts_by_irrigation,</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Pairwise Comparisons of Weed-Control Treatments Within Each Irrigation Method"</span></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Pairwise Comparisons of Weed-Control Treatments Within Each Irrigation Method</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">contrast</th>
<th style="text-align: left;">Irrigation</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">t.ratio</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Herbicide A - Herbicide B</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: right;">-8.8000000</td>
<td style="text-align: right;">1.154605</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-7.6216549</td>
<td style="text-align: right;">0.0000180</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide A - Herbicide B</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: right;">-0.4783333</td>
<td style="text-align: right;">1.154605</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-0.4142831</td>
<td style="text-align: right;">0.6874131</td>
</tr>
</tbody>
</table>
</div>
</div>
<section id="simple-effect-of-weed-treatments-in-each-irrigation-method" class="level3">
<h3 class="anchored" data-anchor-id="simple-effect-of-weed-treatments-in-each-irrigation-method">Simple Effect of Weed Treatments in each Irrigation Method</h3>
<p>Table 8 shows the estimated corn yield for each weed treatment under drip irrigation and sprinkler irrigation. Dunnett comparisons against the control are not performed within each irrigation method. Doing so would incorrectly treat the control as if it belonged to both drip and sprinkler irrigation.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co">#-------------------------------------------------------#</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Simple effects of active weed treatment within each irrigation method</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co">#------------------------------------------------------#</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>emm_irrigation_by_weed <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>  factorial_model,</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Weed <span class="sc">|</span> Irrigation</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>  emm_irrigation_by_weed,</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Simple Effects of Irrigation Method Within Each Weed-Control Treatment"</span></span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Simple Effects of Irrigation Method Within Each Weed-Control Treatment</caption>
<colgroup>
<col style="width: 17%">
<col style="width: 16%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 13%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Weed</th>
<th style="text-align: left;">Irrigation</th>
<th style="text-align: right;">emmean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">lower.CL</th>
<th style="text-align: right;">upper.CL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: right;">113.6467</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">110.3943</td>
<td style="text-align: right;">116.8991</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: right;">122.4467</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">119.1943</td>
<td style="text-align: right;">125.6991</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Herbicide A</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: right;">114.1950</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">110.9426</td>
<td style="text-align: right;">117.4474</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide B</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: right;">114.6733</td>
<td style="text-align: right;">1.465576</td>
<td style="text-align: right;">10.30618</td>
<td style="text-align: right;">111.4209</td>
<td style="text-align: right;">117.9257</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="comparison-of-weed-treatments-in-each-irrigation-method" class="level3">
<h3 class="anchored" data-anchor-id="comparison-of-weed-treatments-in-each-irrigation-method">Comparison of Weed Treatments in each Irrigation Method</h3>
<p>Table 9 shows the comparison between Herbicides A and B within each irrigation method. From Table 9, estimated difference between Herbicides A and B within Drip irrigation was <span class="math inline">\(-8.80\)</span> with p-value far less than <span class="math inline">\(0.05\)</span>. Also, the estimated difference between Herbicides A and B within Sprinkler irrigation was <span class="math inline">\(-0.47\)</span> with p-value <span class="math inline">\(0.68\)</span>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Compare irrigation methods within each active weed-control treatment</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>irrigation_contrasts <span class="ot">&lt;-</span> <span class="fu">contrast</span>(</span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a>  emm_irrigation_by_weed,</span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"pairwise"</span></span>
<span id="cb15-5"><a href="#cb15-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb15-6"><a href="#cb15-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-7"><a href="#cb15-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb15-8"><a href="#cb15-8" aria-hidden="true" tabindex="-1"></a>  irrigation_contrasts,</span>
<span id="cb15-9"><a href="#cb15-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Pairwise Comparisons of Weed Treatment Within Each Irrigation Method"</span></span>
<span id="cb15-10"><a href="#cb15-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Pairwise Comparisons of Weed Treatment Within Each Irrigation Method</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 3%">
<col style="width: 13%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">contrast</th>
<th style="text-align: left;">Irrigation</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">t.ratio</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Herbicide A - Herbicide B</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: right;">-8.8000000</td>
<td style="text-align: right;">1.154605</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-7.6216549</td>
<td style="text-align: right;">0.0000180</td>
</tr>
<tr class="even">
<td style="text-align: left;">Herbicide A - Herbicide B</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: right;">-0.4783333</td>
<td style="text-align: right;">1.154605</td>
<td style="text-align: right;">10</td>
<td style="text-align: right;">-0.4142831</td>
<td style="text-align: right;">0.6874131</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="main-effects-of-irrigation-methods" class="level3">
<h3 class="anchored" data-anchor-id="main-effects-of-irrigation-methods">Main Effects of Irrigation Methods</h3>
<p>Table 10 shows estimated marginal means for drip and sprinkler irrigation. This helps determine whether irrigation method has a similar or different effect on corn yield.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimated marginal means for irrigation method</span></span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>emm_irrig <span class="ot">&lt;-</span> <span class="fu">emmeans</span>(</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>  split_model,</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>  <span class="sc">~</span> Irrigation</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>  emm_irrig,</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Estimated Marginal Means for Irrigation Method"</span></span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Estimated Marginal Means for Irrigation Method</caption>
<colgroup>
<col style="width: 4%">
<col style="width: 15%">
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Irrigation</th>
<th style="text-align: left;">Control</th>
<th style="text-align: right;">emmean</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">lower.CL</th>
<th style="text-align: right;">upper.CL</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">1</td>
<td style="text-align: left;">Drip</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">118.04667</td>
<td style="text-align: right;">1.515828</td>
<td style="text-align: right;">7.490144</td>
<td style="text-align: right;">114.50931</td>
<td style="text-align: right;">121.58403</td>
</tr>
<tr class="even">
<td style="text-align: left;">2</td>
<td style="text-align: left;">Sprinkler</td>
<td style="text-align: left;">n</td>
<td style="text-align: right;">114.43417</td>
<td style="text-align: right;">1.515828</td>
<td style="text-align: right;">7.490144</td>
<td style="text-align: right;">110.89681</td>
<td style="text-align: right;">117.97153</td>
</tr>
<tr class="odd">
<td style="text-align: left;">6</td>
<td style="text-align: left;">None</td>
<td style="text-align: left;">y</td>
<td style="text-align: right;">91.54167</td>
<td style="text-align: right;">1.625625</td>
<td style="text-align: right;">9.816736</td>
<td style="text-align: right;">87.91036</td>
<td style="text-align: right;">95.17297</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="comparison-of-irrigation-methods" class="level3">
<h3 class="anchored" data-anchor-id="comparison-of-irrigation-methods">Comparison of Irrigation Methods</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Comparison of irrigation methods </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>irrigation_contrasts <span class="ot">&lt;-</span> <span class="fu">contrast</span>(</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>  emm_irrig,</span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">method =</span> <span class="st">"pairwise"</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a>  irrigation_contrasts,</span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">caption =</span> <span class="st">"Pairwise Comparisons of Irrigation Method"</span></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Pairwise Comparisons of Irrigation Method</caption>
<colgroup>
<col style="width: 30%">
<col style="width: 13%">
<col style="width: 13%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">contrast</th>
<th style="text-align: right;">estimate</th>
<th style="text-align: right;">SE</th>
<th style="text-align: right;">df</th>
<th style="text-align: right;">t.ratio</th>
<th style="text-align: right;">p.value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Drip n - Sprinkler n</td>
<td style="text-align: right;">3.6125</td>
<td style="text-align: right;">1.212386</td>
<td style="text-align: right;">7.854778</td>
<td style="text-align: right;">2.979662</td>
<td style="text-align: right;">0.0425468</td>
</tr>
<tr class="even">
<td style="text-align: left;">Drip n - None y</td>
<td style="text-align: right;">26.5050</td>
<td style="text-align: right;">1.347146</td>
<td style="text-align: right;">11.945650</td>
<td style="text-align: right;">19.674927</td>
<td style="text-align: right;">0.0000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sprinkler n - None y</td>
<td style="text-align: right;">22.8925</td>
<td style="text-align: right;">1.347146</td>
<td style="text-align: right;">11.945650</td>
<td style="text-align: right;">16.993332</td>
<td style="text-align: right;">0.0000000</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
</section>
<section id="conclusion" class="level2">
<h2 class="anchored" data-anchor-id="conclusion">Conclusion</h2>
<p>In this chapter, we considered a split-plot design with a control using an irrigation and weed-control example. Irrigation method was treated as the whole plot factor because it is difficult to randomize at the small subplot level. Weed treatment was treated as the split plot factor because it can be applied more easily to smaller subplots.</p>
<p>The factorial portion of the design included two irrigation methods and two active weed treatments. The four factorial treatment combinations were drip irrigation with herbicide A, drip irrigation with herbicide B, sprinkler irrigation with herbicide A, and sprinkler irrigation with herbicide B.</p>
<p>The control treatment was included as a separate extra treatment outside the factorial structure. This means the control was not treated as a level of the weed factor and was not assigned to a specific irrigation method. Instead, the control served as a baseline treatment that could be compared with the average of the factorial treatment combinations.</p>
<p>The mixed model accounted for block-to-block variation and whole plot variation by including random effects for block and whole plot within block. The irrigation effect was evaluated using the correct whole plot structure, while the weed effect and the irrigation by weed interaction were evaluated using the subplot structure.</p>
<p>Overall, the split-plot design allows researchers to correctly analyze experiments where one factor is harder to randomize than another. When a control is included as an extra treatment, it should be modeled separately rather than forced into the factorial treatment structure. This preserves the correct interpretation of the irrigation effect, the weed effect, the interaction effect, and the treatment-versus-control comparison.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>